import { Metadata } from "next";
import "../../globals.css";
import { AuthProvider } from "@/context/AuthContext";

import Sidebar from "@/components/admin/Sidebar";
import Header from "@/components/admin/Header";

export const metadata: Metadata = {
  title: "Cortex Blog CMS",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={"min-h-screen flex flex-col antialiased"}
        cz-shortcut-listen="true"
      >
        <AuthProvider>
          <div className="flex h-screen bg-gray-100">
            {/* Sidebar */}
            <Sidebar />

            {/* Main Content */}
            <div className="flex flex-col flex-1">
              <Header />
              <main className="flex-1 p-6 overflow-y-auto">{children}</main>
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
