import { Metadata } from "next";
import "../../globals.css";
import { AuthProvider } from "@/context/AuthContext";

import Sidebar from "@/components/admin/Sidebar";
import Header from "@/components/admin/Header";

export const metadata: Metadata = {
  title: "Cortex Blog CMS",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={"min-h-screen flex flex-col antialiased"}
        cz-shortcut-listen="true"
      >
        <AuthProvider>
          <div className="flex h-screen bg-background text-foreground">
            {/* Sidebar */}
            <Sidebar />

            {/* Main Content */}
            <div className="flex flex-col flex-1 overflow-hidden relative">
              <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 pointer-events-none mix-blend-soft-light z-0"></div>
              <Header />
              <main className="flex-1 p-8 overflow-y-auto relative z-10 scrollbar-hide">
                {children}
              </main>
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
